# Request
################################################################################
# if auton = true, run autonomous dig                                          #
# if auton = false, fall back onto position goal.                              #
# if position data is null, fall back onto power goal.                         #
# if power data is also null, do nothing.                                      #
################################################################################

# Type 1: Full manual control (Power)
float32 dig_link_pwr_goal
float32 dig_bckt_pwr_goal
# Type 2: Position control
float32 dig_link_pos_goal
float32 dig_bckt_pos_goal
# Type 3: Autonomous control
# apparently you can only use the std_srvs/Trigger for services not actions?
bool auton
---
# Result
float32 est_dig_link_goal
float32 est_dig_bckt_goal
---
# Feedback
float32 percent_link_done
float32 percent_bckt_done
