# Request
################################################################################
# if auton = true, run autonomous dig                                          #
# if auton = false, and pos = true, position goal.                             #
# if auton = false and pos = false, power goal.                                #
################################################################################

# Type 1: Full manual control (Power)
float32 link_pwr_goal -987654.321
float32 bckt_pwr_goal -987654.321
float32 vibr_pwr_goal -987654.321
# Type 2: Position control
float32 link_pos_goal -987654.321
float32 bckt_pos_goal -987654.321
float32 hstp_pos_goal -987654.321
# it doesn't make sense to have a position goal for vibration motors. use power.
# Type 3: Autonomous control
# apparently you can only use the std_srvs/Trigger for services not actions?
# unfortunately, it doesnt seem you can detect whether data was sent or not.
bool scoop false
bool dig_to_dump false
---
# Result
float32 est_link_goal
float32 est_bckt_goal
float32 est_vibr_goal
---
# Feedback
float32 percent_link_done
float32 percent_bckt_done
float32 percent_vibr_done
