/dig_action_server:
  ros__parameters:
    left_linkage_offset: -0.100099
    right_linkage_offset: -0.395029
    left_bucket_offset: -0.452916
    right_bucket_offset: 0.031417
    use_sim_time: false
