/dig_action_server:
  ros__parameters:
    left_linkage_offset: -0.539063
    right_linkage_offset: -0.947510
    left_bucket_offset: 0.814453
    right_bucket_offset: 0.727295
    use_sim_time: false