/dig_action_server:
  ros__parameters:
    left_linkage_offset: -0.520997
    right_linkage_offset: 0.042139
    left_bucket_offset: -0.183594
    right_bucket_offset: 0.061202
    use_sim_time: false
