/dig_action_server:
  ros__parameters:
    left_bucket_offset: 0.067383
    left_linkage_offset: -0.443848
    right_bucket_offset: 0.315918
    right_linkage_offset: -0.341309
    use_sim_time: false