ukf_node:
  ros__parameters:  
    frequency: 15.0
    sensor_timeout: 1.9
    two_d_mode: false
    publish_tf: false
    # frames
    # map_frame: "map"
    odom_frame: odom
    base_link_frame: base_link
    debug: true
    debug_out_file: /home/astrobotics/Downloads/odom_out.txt
    print_diagnostics: true

    # pose0:
    #   topic: '/arucopose'
    #   # frame_id: "base_link"
    #   config: [true,  true,  true,     # x y z
    #           true,  true,  true,     
    #           false, false, false,    
    #           false, false, false,    
    #           false, false, false]    
    #   differential: false
    #   relative:     false
    pose0: /pose_0
    pose0_config: [true,  true,  true,     # x y z
              false,  false,  false,      #do we want yaw from aruco?
              false, false, false,    
              false, false, false,    
              false, false, false]
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 5
    pose0_rejection_threshold: 2.0

    pose1: /drive/pose/covariance
    pose1_config: [true,  true,  true,     # x y z
              false,  false,  true,     #only want yaw from drivetrain - IMU based
              false, false, false,    
              false, false, false,    
              false, false, false]
    pose1_differential: false
    pose1_relative: false
    pose1_queue_size: 5
    pose1_rejection_threshold: 2.0



    
      # queue_size:   5
      # rejection_threshold: 2.0 #rejection threshold, may not be needed
    # pose1:
    #   topic: "drive/pose" #drive pose
    #   config: [false, false, false,
    #           true,  true,  true,
    #           false, false, false,
    #           true,  true,  true,
    #           true,  true,  true]
    #   differential: false
    #   relative: false
    #   queue_size: 5
    #   #rejection_threshold: 2.0 
      
    # process_noise_covariance: [0.05, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.05, 0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.06, 0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.03, 0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.03, 0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.06, 0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.025, 0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.025, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.04, 0.0,    0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.01, 0.0,    0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.01, 0.0,    0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.02, 0.0,    0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.01, 0.0,    0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.01, 0.0,
    #                                0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.0,     0.0,     0.0,    0.0,    0.0,    0.0,    0.0,    0.0,    0.015]
      
