ukf_node:
  ros__parameters:  
    frequency: 15.0
    sensor_timeout: 1.9
    two_d_mode: false
    publish_tf: false
    # frames
    # map_frame: "map"
    odom_frame: odom
    base_link_frame: base_link
    debug: true
    debug_out_file: /home/astrobotics/Downloads/odom_out.txt
    print_diagnostics: true

    pose0: /pose_0
    pose0_config: [true,  true,  true,     # x y z
              false,  false,  false,      #do we want yaw from aruco?
              false, false, false,    
              false, false, false,    
              false, false, false]
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 5
    pose0_rejection_threshold: 2.0

    pose1: /drive/pose/covariance
    pose1_config: [true,  true,  true,     # x y z
              false,  false,  true,     #only want yaw from drivetrain - IMU based
              false, false, false,    
              false, false, false,    
              false, false, false]
    pose1_differential: false
    pose1_relative: false
    pose1_queue_size: 5
    pose1_rejection_threshold: 2.0
      
