# config/arenas.yaml
arenas:
  KSC:
    frames:
      - parent: "world"
        child:  "field_origin"
        x:       0.0
        y:       0.0
        z:       0.0
        yaw:     0.0

      - parent: "field_origin"
        child:  "starting_zone_center"
        x:       1.0
        y:       1.0
        z:       0.0
        yaw:     0.0

      # Obstacle Zone center
      - parent: "field_origin"
        child:  "obstacle_zone_center"
        x:       1.94
        y:       2.50
        z:       0.0
        yaw:     0.0

      # Column center
      - parent: "field_origin"
        child:  "column_center"
        x:       3.88
        y:       2.50
        z:       0.0
        yaw:     0.0

      # Excavation Zone center
      - parent: "field_origin"
        child:  "excavation_zone_center"
        x:       5.38
        y:       3.75
        z:       0.0
        yaw:     0.0

      # Construction Zone center
      - parent: "field_origin"
        child:  "construction_zone_center"
        x:       5.38
        y:       1.25
        z:       0.0
        yaw:     0.0

      # Berm center
      - parent: "field_origin"
        child:  "berm_center"
        x:       5.38
        y:       0.60
        z:       0.0
        yaw:     0.0

      # Optional: start‐zone corners
      - parent: "field_origin"
        child:  "starting_zone_bl"
        x:       0.0
        y:       0.0
        z:       0.0
        yaw:     0.0

      - parent: "field_origin"
        child:  "starting_zone_tr"
        x:       2.0
        y:       2.0
        z:       0.0
        yaw:     0.0

    shapes:
      starting_zone:
        type:   rectangle
        center: [1.0, 1.0]
        size:   [2.0, 2.0]

      obstacle_zone:
        type:   rectangle
        center: [1.94, 2.5]
        size:   [3.88, 5.0]

      berm:
        type:   rectangle
        center: [5.38, 0.6]
        size:   [2.0, 1.0]

      rock1:
        type:   circle
        center: [2.5, 4.0]
        radius: 0.3

  arena2:
    frames: []
    shapes: {}

  arena3:
    f
