name: astrodev

services:
  dev-container:
    image: vtastrobotics/astro-dev:main
    build:
      dockerfile: "Dockerfile"
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - ..:/workspace:cached
      - /dev:/dev:bind
    command: sleep infinity

    #  "runArgs": [
		#  "--cap-add=SYS_PTRACE", // Allows the container to trace processes using ptrace system call
		#  "--security-opt=seccomp=unconfined", // Disables seccomp security profiles for the container
		#  "--ipc=host", // Shares the host's IPC namespace with the container
		#  "--network=host", // Shares the host's network namespace with the container
		#  "--pid=host", // Shares the host's PID namespace with the container
		#  "--privileged", // Gives the container full access to the host's devices and allows it to run with root privileges
    #  ],
  microros-agent:
     image: microros/micro-ros-agent:humble
     privileged: true
     network_mode: host
     volumes:
       - /dev:/dev
     command: serial --dev /dev/ttyACM0 -b 115200
