ukf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    two_d_mode: false
    publish_tf: true
    # frames
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"

    # Example: subscribe to a PoseWithCovarianceStamped on /aruco_pose_cov
    pose0:
      topic: "/aruco_pose"
      frame_id: "camera_link"
      pose0_config: [true, true, true,
                     true, true, true]
      differential: false
      relative: false
      queue_size: 5
