name: CI

on:
  workflow_run:
    workflows: [Main-Branch-Update]
    types: [completed]

env:
  DEV_CONTAINER_NAME: astro-dev

jobs:
  apply-cpp-formatting:
    name: Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Get Docker tag
        run: echo "CUR_DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}${{ github.event.workflow_run.outputs.cur_docker_tag }}" >> $GITHUB_ENV

      - name: Test
        run: echo "what is the value of CUR_DOCKER_TAG? ${{ env.CUR_DOCKER_TAG }}"

  #     - name: Run code formatting (clang-format and clang-tidy)
  #       run: docker run
  #         --rm
  #         -e GITHUB_EVENT_PATH=$GITHUB_EVENT_PATH
  #         -v /home/runner/:/home/runner/
  #         ${{ env.CUR_DOCKER_TAG }}
  #         sudo bash -c "cd /home/astro-dev/src/ && chmod u+x entrypoint.sh && chmod -R u+r /home/ && source entrypoint.sh"
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # build-src-code:
  #   name: Build source code
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Waste time # TODO
  #       run: sleep 10
  #     - name: Check out repository
  #       uses: actions/checkout@v3

  #     - name: Get Docker tag
  #       run: echo "CUR_DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}${{ github.event.workflow_run.outputs.cur_docker_tag }}" >> $GITHUB_ENV

  #     - name: Build our source code in our developer container
  #       run: |
  #         docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c "
  #           cd /home/astro-dev/src/;
  #           source build_scripts/build.sh 2> >(tee err.log >&2);
  #           if [ -s err.log ]; then
  #             echo Build failed due to output in stderr. Yes, this fails on warnings. Fix them.;
  #             exit 1;
  #           fi
  #           "
