name: C++ Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Copy formatting
        run: cp ./.clang-format ./.github/actions/cppformat

      - name: Copy formatting
        run: cp ./.clang-tidy ./.github/actions/cppformat

      - name: Copy src for formatting
        run: cp -r ./src ./.github/actions/cppformat

      - name: Copy Dockerfile
        run: cp ./.devcontainer/Dockerfile ./.github/actions/cppformat

      - name: Clang Code Formatter
        uses: ./.github/actions/cppformat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
