name: C++ Formatting

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: clang-format Code Formatter
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Copy Dockerfile
        run: cp ./.devcontainer/Dockerfile ./.github/actions/cppformat

      - name: Modify Dockerfile for clang testing
        run: echo "COPY ./.github/actions/cppformat/entrypoint.sh /entrypoint.sh\nRUN chmod +x /entrypoint.sh\nENTRYPOINT [\"/entrypoint.sh\"]" >> ./.github/actions/cppformat/Dockerfile
"
      - name: Clang Code Formatter
        uses: ./.github/actions/cppformat
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
