name: On Main Branch Update

on:
  push:
    branches:
      - main

jobs:
  run-on-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull branch dev container image
        id: pull_branch_image
        run: docker pull vtastrobotics/astro-dev:main

      - name: Build and push the developer container image
        run: |
          docker build --file ./.github/actions/cppformat/Dockerfile --tag vtastrobotics/astro-dev:main .
          docker push vtastrobotics/astro-dev:main

