name: Workflow 1

on:
  push:
    branches:
      - features/phoenix_actions

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Workflow 1 completed!"
